#include <gtk/gtk.h>
#include "lexer.h" // Generated by Flex
#include "tokens.h"

void apply_syntax_highlighting(GtkTextBuffer *buffer) {
    GtkTextIter start, end;
    gchar *text;
    extern char *yytext;
    extern int yylex();

    gtk_text_buffer_get_start_iter(buffer, &start);
    gtk_text_buffer_get_end_iter(buffer, &end);
    text = gtk_text_buffer_get_text(buffer, &start, &end, FALSE);

    // Set the Lex input
    YY_BUFFER_STATE buffer_state = yy_scan_string(text);

    // Clear all tags
    gtk_text_buffer_remove_all_tags(buffer, &start, &end);

    GtkTextIter iter;
    gtk_text_buffer_get_start_iter(buffer, &iter);

    int token;
    int offset = 0; // Track the current character offset

    while ((token = yylex()) != 0) {
        GtkTextTag *tag = NULL;
        GtkTextTagTable *tag_table = gtk_text_buffer_get_tag_table(buffer);

        // Match token types with highlighting tags
        switch (token) {
            case KEYWORD: tag = gtk_text_tag_table_lookup(tag_table, "keyword"); break;
            case TYPE: tag = gtk_text_tag_table_lookup(tag_table, "type"); break;
            case HEADER: tag = gtk_text_tag_table_lookup(tag_table, "header"); break;
            case STRING: tag = gtk_text_tag_table_lookup(tag_table, "string"); break;
            case COMMENT: tag = gtk_text_tag_table_lookup(tag_table, "comment"); break;
            case PREPROC: tag = gtk_text_tag_table_lookup(tag_table, "preprocessor"); break;
            case FUNCTION: tag = gtk_text_tag_table_lookup(tag_table, "function"); break;
            case VARIABLE: tag = gtk_text_tag_table_lookup(tag_table, "variable"); break;
            case NUMBER: tag = gtk_text_tag_table_lookup(tag_table, "number"); break;
            case OPERATOR: tag = gtk_text_tag_table_lookup(tag_table, "operator"); break;
            case SPECIAL: tag = gtk_text_tag_table_lookup(tag_table, "special"); break;
        }

        if (!tag) continue; // Skip if the tag doesn't exist

        // Calculate token's start and end positions
        int token_length = g_utf8_strlen(yytext, -1);
        GtkTextIter token_start, token_end;
        gtk_text_buffer_get_iter_at_offset(buffer, &token_start, offset);
        gtk_text_buffer_get_iter_at_offset(buffer, &token_end, offset + token_length);

        // Apply the tag
        gtk_text_buffer_apply_tag(buffer, tag, &token_start, &token_end);

        // Update offset
        offset += token_length;
    }

    yy_delete_buffer(buffer_state);
    g_free(text);
}

void on_buffer_changed(GtkTextBuffer *buffer, gpointer data) {
    apply_syntax_highlighting(buffer);
}

int main(int argc, char *argv[]) {
    GtkWidget *window, *text_view, *scrolled_window;
    GtkTextBuffer *buffer;

    gtk_init(&argc, &argv);

    // Create window
    window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_window_set_title(GTK_WINDOW(window), "Text Editor with Syntax Highlighting");
    gtk_window_set_default_size(GTK_WINDOW(window), 600, 400);
    g_signal_connect(window, "destroy", G_CALLBACK(gtk_main_quit), NULL);

    // Create scrolled text view
    scrolled_window = gtk_scrolled_window_new(NULL, NULL);
    text_view = gtk_text_view_new();
    gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(text_view), GTK_WRAP_WORD); // Enable word wrapping

 
    buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(text_view));
    g_signal_connect(buffer, "changed", G_CALLBACK(on_buffer_changed), NULL);

    gtk_container_add(GTK_CONTAINER(scrolled_window), text_view);
    gtk_container_add(GTK_CONTAINER(window), scrolled_window);

    // Add syntax highlighting tags
    gtk_text_buffer_create_tag(buffer, "keyword", "foreground", "cyan", NULL);
    gtk_text_buffer_create_tag(buffer, "type", "foreground", "green", NULL);
    gtk_text_buffer_create_tag(buffer, "header", "foreground", "purple", NULL);
    gtk_text_buffer_create_tag(buffer, "string", "foreground", "yellow", NULL);
    gtk_text_buffer_create_tag(buffer, "comment", "foreground", "gray", NULL);
    gtk_text_buffer_create_tag(buffer, "preprocessor", "foreground", "magenta", NULL);
    gtk_text_buffer_create_tag(buffer, "function", "foreground", "blue", NULL);
    gtk_text_buffer_create_tag(buffer, "variable", "foreground", "white", NULL);
    gtk_text_buffer_create_tag(buffer, "number", "foreground", "red", NULL);
    gtk_text_buffer_create_tag(buffer, "operator", "foreground", "white", NULL);
    gtk_text_buffer_create_tag(buffer, "special", "foreground", "magenta", NULL);

    gtk_widget_show_all(window);
    gtk_main();

    return 0;
}
